### ISSUE TITLE
$EDITOR cannot be multiply words, eg: `subl3 -w`

### ISSUE THREAD

**Issue by andlrc** [seletskiy/zsh-fuzzy-search-and-edit#3]
`$EDITOR` cannot contain multiply words eg, `subl3 -w` since zsh doesn't do word splitting by default, either use:

```
eval "$EDITOR" "$file" "+$line" < /dev/tty
```

which is POSIX compatible or use the zsh word splitting syntax:

```
"${=EDITOR}" "$file" "+$line" < /dev/tty
```

instead of:

```
$EDITOR "$file" "+$line" < /dev/tty
```

**Comment by seletskiy** [comment]
`eval "$EDITOR" "$file"` is not correct one, since it will misbehave on filenames with spaces.

**Comment by andlrc** [comment]
Good point, this can however be avoided with:

```
eval "$EDITOR" "$(printf "%q" "$file")"
```

Which isn't POSIX though, but since `printf` is a build-in it will work. Alternative you can use the word splitting syntax:

```
"${=EDITOR}" 
```

**Comment by seletskiy** [comment]
@andlrc: I've already pushed `${=EDITOR}` variant, thanks.
