### ISSUE TITLE
Injecting the tty device for windowed editors breaks the editor

### ISSUE THREAD

**Issue by mtalexan** [seletskiy/zsh-fuzzy-search-and-edit#8]
If the `${=EDITOR}` is set to a windowed editor by default, the `</dev/tty` portion of the editor command causes errors.  The extra tty argument causes errors in most windowed editors when during opening of the file that makes the whole command fail.
The obvious work around would be to make the editor open directly in the terminal, but that's not always desirable.  
```
 "${=EDITOR} "+${line}" "${file}" </dev/tty
``` 

Having the tty injected optionally would be the easiest solution to implement, while a less useful option might be to allow a variable to be set that contains extra options to provide to the EDITOR when opening the file.

<b>Edit</b>
I just discovered what the `${=VARIABLE_NAME}` does.  I've removed my incorrect comments about the `EDITOR` variable not being able to include command-line arguments to the program since the purpose of the `${=` is to split the variable on spaces into separate arguments.

**Comment by seletskiy** [comment]
@mtalexan I like option approach. It would be nice if you could open a PR for that.

**Comment by mtalexan** [comment]
I'll get on it as soon as I get a chance.

Do you prefer an option to use visual editor vs non-visual editor?  That would make the line look like:
```
if [ -n "${NAME_OF_SETTINGS_VARIABLE}" ] ; then
    "${=VISUAL_EDITOR}" "+${line}" "${file}" 
else
    "${=EDITOR}" "+${line}" "${file}" < /dev/tty
fi
```
Or I can make it an option that only controls whether the `tty` is injected.
```
if [ -n "${NAME_OF_SETTINGS_VARIABLE}" ] ; then
    "${=EDITOR}" "+${line}" "${file}" 
else
    "${=EDITOR}" "+${line}" "${file}" < /dev/tty
fi
```

Do you have a preference?  I think you said you prefer my proposal that would look like the second case, and I think that would provide better support for your average user who has to deal with a lot of tools using `EDITOR` instead of `VISUAL_EDITOR` (which would fall thru to `EDITOR` in a console-only environment).
